### ISSUE TITLE
Volume Music Bug i think 

### ISSUE THREAD

**Issue by Ozaa** [Fabricio20/LewdWiki#100]
Hi !
When i try to Change the volume of LewdBot's music He say me : "  This command is restricted to POWER users only." But i'm the Owner of the Server and i'm admin of LewdBot 
Can you help me please
Oza

**Comment by Fabricio20** [comment]
A power user is a donor (https://patreon.com/Fabricio20). To be able to change the volume globally, you need to be a donor, however, you can change the volume locally by right clicking the bot and dragging the volume bar. We require donor status because lowering the volume globally is a CPU-expensive task and if it was free, LewdBot wouldn't be able to operate.

**Comment by Ozaa** [comment]
Okay thanks you and sorry for this
