### ISSUE TITLE
Problem on iOS version of Discord

### ISSUE THREAD

**Issue by DynamOrchid** [Fabricio20/LewdWiki#127]
So,I've been using the iOS application for Discord,and sometimes I connect to a LewdBot radio to listen to some music. But,there is a problem: the music sounds like if I was listening to music in another app and getting a call. It didn't do that before until recently. The music quality is horrible with this issue,and the desktop version doesn't have the problem. I guess there was a change somewhere that changed LewdBot music ability to be considered like someone talking to be changed to actual music playing. It's still annoying,so I hope I get an answer here.

**Comment by Fabricio20** [comment]
You probably want to ask Discord staff about this, I didn't change anything and any changes I make affect all versions of Discord, be it Desktop, iOS, Android. All of them will be affected the exact same way.

LewdBot and _any_ other music bots are users that connect to channels and start talking, that's exactly how this works, so it's probably something on your phone that changed (some config perhaps) or the Discord app for iOS was updated and now has an issue with voice.

There is really _nothing_ I can do to diagnose this because it's not happening on desktop, which means it's not an issue on my part.

**Comment by Fabricio20** [comment]
"If you are using a bluetooth headset, it could be the cause because bluetooth tends to reduce the receiving quality while the microphone is working". - Necroforger#5890

Just a guess though.
