### ISSUE TITLE
Major things are missing!

### ISSUE THREAD

**Issue by brandonMCGEE** [Fabricio20/LewdWiki#78]
music isnt working the commands arnt showing up, !hentai, !lewd, !music arnt working or their and those are just the 3 that arnt working! help!

**Comment by Fabricio20** [comment]
I'm currently aware of the issue and trying on fixes.

Earlier today my hosting provider shut down all my services for no apparent reason and caused a corruption on my database server, I managed to restore it without any losses but I terminated the dedicated server that ran LewdBot.

Since she is now on a different server on a different provider, it takes some time to tacke all the issues.

**Comment by brandonMCGEE** [comment]
ok good to know!  Hope it come back all together well!

**Comment by Fabricio20** [comment]
We are now 100% back, still monitoring in case anything else happens.

**Comment by brandonMCGEE** [comment]
the !hentai command doesnt work 
LewdBotBOT - Today at 9:49 AM
brandon: Error while searching for images

**Comment by Fabricio20** [comment]
Should be fixed by now, reopen the issue if not.
